name: Unified TypeScript Auto-Fix

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  # Allow manual triggering
  workflow_dispatch:
  # Run on pull requests to main branch
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ts'
      - '**/*.tsx'

jobs:
  auto-fix:
    name: Run TypeScript Auto-Fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Unified TypeScript Auto-Fix
        run: node scripts/unified-auto-fix.js

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Auto-fix TypeScript errors [skip ci]"

      - name: Push changes
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true' && github.event_name == 'schedule'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto-fix TypeScript errors
          title: '[Automated] Fix TypeScript errors'
          body: |
            This PR was automatically created by the Unified TypeScript Auto-Fix system.

            It fixes TypeScript errors in the codebase, including:
            - 'e' is of type 'unknown' errors in event handlers
            - "use client" directive placement
            - React Fragment usage for null returns
            - Missing type annotations for rest parameters
            - Issues with object access on possibly undefined values

            Please review the changes carefully before merging.
          branch: auto-fix-typescript
          base: main
          labels: automated-pr, typescript
