name: Auto-Fix System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  auto-fix:
    name: Auto-Fix Code Quality Issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Unified Auto-Fix System
        run: node scripts/unified-auto-fix.js

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🤖 Auto-Fix: Code quality improvements [skip ci]"

      - name: Push changes
        if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create PR for changes
        if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Auto-Fix: Code quality improvements"
          title: "🤖 Auto-Fix: Code quality improvements"
          body: |
            This PR contains automated fixes for code quality issues.

            Changes include:
            - ESLint auto-fixes
            - TypeScript improvements (using the TypeScript Auto-Fix System)
            - Import organization
            - Unused code removal
            - Type safety enhancements

            The TypeScript Auto-Fix System has automatically fixed common TypeScript errors by:
            - Adding missing type annotations
            - Fixing interface extensions
            - Adding null checks
            - Fixing import statements
            - Addressing unused variables
            - And more!

            The Auto-Learning System has analyzed remaining TypeScript errors and:
            - Identified new error patterns
            - Added new fix strategies to the error-patterns.json file
            - Made the system smarter for future runs
            - Logged all learning activities for review

            The Type Assertions Fixer has automatically fixed:
            - Incorrect type assertions in destructuring patterns
            - Type annotations in function parameters
            - Type annotations in method calls
            - And other common TypeScript syntax errors

            The Advanced Type Fixer has:
            - Used machine learning to identify complex error patterns
            - Generated intelligent fixes for difficult TypeScript errors
            - Added new patterns to the error database for future runs
            - Provided detailed recommendations for improving type safety

            The Specific Error Fixer has:
            - Targeted and fixed known TypeScript errors in specific files
            - Addressed issues with exported member names
            - Fixed "use client" directive placement
            - Corrected event handler type issues
            - Resolved null/undefined checks
            - Fixed React component issues

            The Enhanced Specific Error Fixer has:
            - Provided more comprehensive fixes for TypeScript errors
            - Fixed event handler type issues with proper React types
            - Improved "use client" directive placement
            - Added optional chaining for null/undefined checks
            - Fixed import statement issues
            - Resolved type conversion problems
            - Added proper type assertions
            - Fixed component-specific issues

            Please review these changes carefully before merging.
          branch: auto-fix-${{ github.run_id }}
          base: ${{ github.head_ref }}

      - name: Generate quality report
        run: |
          mkdir -p reports
          npm run quality:report || true

      - name: Upload quality report
        uses: actions/upload-artifact@v3
        with:
          name: quality-reports
          path: reports/
          retention-days: 7

  quality-gate:
    name: Quality Gate
    needs: auto-fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript
        run: npx tsc --noEmit

      - name: Check ESLint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx --max-warnings=0

      - name: Create issue for remaining problems
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/quality-issues.md
          update_existing: true
